global using System.Buffers;
global using System.Collections.Frozen;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Globalization;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Net;
global using System.Threading.Channels;
global using Android.App;
global using Android.Bluetooth;
global using Android.Content.PM;
global using Android.Content;
global using Android.Graphics.Drawables;
global using Android.Media.Projection;
global using Android.Media;
global using Android.OS;
global using Android.Runtime;
global using Android.Util;
global using Android;
global using AuraMusic.Kernel.Codec;
global using AuraMusic.Kernel.Localization;
global using AuraMusic.Kernel.Multipath;
global using AuraMusic.Kernel.Playout;
global using AuraMusic.Kernel.Protocol;
global using AuraMusic.Kernel.Spectrum;
global using AuraMusic.Kernel.State;
global using AuraMusic.Kernel.Updates;
global using AuraMusic.Mobile.Casting;
global using AuraMusic.Mobile.Controls;
global using AuraMusic.Mobile.Resources.Strings;
global using AuraMusic.Mobile.Updates;
global using CommunityToolkit.Maui.Extensions;
global using CommunityToolkit.Maui.Views;
global using CommunityToolkit.Maui;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Application = Microsoft.Maui.Controls.Application;
global using AudioEncoding = Android.Media.Encoding;
global using Environment = System.Environment;
global using Image = Microsoft.Maui.Controls.Image;
global using Stream = System.IO.Stream;
global using Timer = System.Threading.Timer;
